{
 "title": "Waterstream",
 "tags": [
  "mqtt",
  "waterstream"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "query": { "query": "mqtt_proxy_clients_current" } }
  ]
 },
 "panels": [
  {
   "title": "Messages Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_proxy_publish_received_total{app=\"$app\"}[1m]))",
     "legendFormat": "received rate, msg/sec"
    },
    {
     "expr": "sum(mqtt_proxy_publish_received_total{app=\"$app\"})",
     "legendFormat": "received total count"
    },
    {
     "expr": "sum(rate(mqtt_proxy_published_to_kafka_total{app=\"$app\"}[1m]))",
     "legendFormat": "kafka publish rate, msg/sec"
    },
    {
     "expr": "sum(mqtt_proxy_published_to_kafka_total{app=\"$app\"})",
     "legendFormat": "kafka total publish count"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_proxy_publish_sent_total{app=\"$app\"}[1m]))",
     "legendFormat": "rate, msg/sec"
    },
    {
     "expr": "sum(mqtt_proxy_publish_sent_total{app=\"$app\"})",
     "legendFormat": "total count"
    },
    {
     "expr": "sum(rate(mqtt_proxy_publish_sent_total{app=\"$app\"}[10m]))",
     "legendFormat": "rate 10m, msg/sec"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_clients_current{app=\"$app\"})",
     "legendFormat": "connected clients"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_subscribe_received_total{app=\"$app\"})",
     "legendFormat": "SUBSCRIBE received"
    },
    {
     "expr": "sum(mqtt_proxy_unsubscribe_received_total{app=\"$app\"})",
     "legendFormat": "UNSUBSCRIBE received"
    },
    {
     "expr": "sum(mqtt_proxy_subscriptions_current{app=\"$app\"})",
     "legendFormat": "Current subscriptions"
    }
   ]
  },
  {
   "title": "Client connections details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_connect_received_total{app=\"$app\"})",
     "legendFormat": "CONNECT received"
    },
    {
     "expr": "sum(mqtt_proxy_accept_sent_total{app=\"$app\"})",
     "legendFormat": "ACCEPT sent"
    },
    {
     "expr": "sum(mqtt_proxy_inactive_clients_disconnected_total{app=\"$app\"})",
     "legendFormat": "Inactive clients disconnected"
    },
    {
     "expr": "sum(mqtt_proxy_connections_closed_total{app=\"$app\"})",
     "legendFormat": "connections closed"
    },
    {
     "expr": "sum(mqtt_proxy_disconnect_received_total{app=\"$app\"})",
     "legendFormat": "DISCONNECT received"
    },
    {
     "expr": "sum(mqtt_proxy_connect_rejected_total{app=\"$app\"})",
     "legendFormat": "connections rejected"
    },
    {
     "expr": "sum(mqtt_proxy_overloaded_clients_disconnected_total{app=\"$app\"})",
     "legendFormat": "overloaded disconnected"
    },
    {
     "expr": "sum(mqtt_proxy_non_initialized_connections_closed_total{app=\"$app\"})",
     "legendFormat": "non-initialized connections closed"
    }
   ]
  },
  {
   "title": "MQTT Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_sessions_fresh_start_count_total{app=\"$app\"})",
     "legendFormat": "Fresh sessions"
    },
    {
     "expr": "sum(mqtt_proxy_sessions_loaded_count_total{app=\"$app\"})",
     "legendFormat": "Loaded sessions"
    },
    {
     "expr": "sum(mqtt_proxy_sessions_not_found_count_total{app=\"$app\"})",
     "legendFormat": "Not found sessions"
    },
    {
     "expr": "sum(mqtt_proxy_sessions_load_duration_total{app=\"$app\"})",
     "legendFormat": "Sessions load duration, ms"
    }
   ]
  },
  {
   "title": "Clients by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_proxy_clients_current{app=\"$app\"}",
     "legendFormat": "Clients on {{instance}}"
    }
   ]
  },
  {
   "title": "Subscription details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_proxy_kafka_consumer_historical_loop_records_",
     "legendFormat": "Historical loop records"
    },
    {
     "expr": "mqtt_proxy_kafka_consumer_historical_loops_number",
     "legendFormat": "Historical loops number"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app=\"$app\", area=\"heap\"}",
     "legendFormat": "Heap usage, bytes ({{instance}})"
    },
    {
     "expr": "jvm_memory_bytes_max{app=\"$app\", area=\"heap\"}",
     "legendFormat": "Heap max size, bytes ({{instance}})"
    },
    {
     "expr": "process_resident_memory_bytes{app=\"$app\"}",
     "legendFormat": "Waterstream process resident memory, bytes ({{instance}})"
    },
    {
     "expr": "jvm_buffer_pool_used_bytes{app=\"$app\", pool=\"direct\"}",
     "legendFormat": "Direct buffers used, bytes ({{instance}})"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_gc_collection_seconds_sum{app=\"$app\"})",
     "legendFormat": "GC Time"
    },
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{app=\"$app\"}[1m]))",
     "legendFormat": "GC Time Fraction"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{app=\"$app\"}",
     "legendFormat": "threads({{state}}, {{instance}})"
    }
   ]
  }
 ]
}